version: 2.1

jobs:
  backend_build:
    working_directory: ~/backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: cd backend && npm install

  frontend_build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm run build

workflows:
  version: 2

  my_workflow:
    jobs:
      - backend_build
      - frontend_build:
          requires:
            - backend_build
